apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
        - name: react-todo
          image: react-todo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
