apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: surajhyadav/reactapp:39a0059
          imagePullPolicy: Always
          ports:
            - containerPort: 80
